Add files via upload

diff --git a/centos_ovpnws b/centos_ovpnws
--- a/centos_ovpnws
+++ b/centos_ovpnws
@@ -13,7 +13,7 @@ elif [[ "$(cat < /etc/system-release-cpe | cut -d: -f5)" == '7' ]]; then
 fi
 yum update -y
 yum --enablerepo=epel install nano wget curl zip unzip git tar gzip bc rc cronie net-tools dos2unix screen yum-utils sudo -y
-yum --enablerepo=epel install openvpn stunnel chkconfig initscripts jq mysql redhat-lsb -y
+yum --enablerepo=epel install openvpn stunnel chkconfig initscripts jq mysql redhat-lsb netcat httpie neofetch vnstat -y
 yum --enablerepo=epel install php php-common php-cli php-pdo php-mysqli php-gd php-pear php-xml php-mbstring php-soap php-snmp php-ldap php-odbc -y
 yum --enablerepo=epel install make gcc libssh2 php-devel php-pearlibssh2-devel -y
 
@@ -74,6 +74,12 @@ cd /etc || exit
 wget 'https://pastebin.com/raw/xtPc5t1k' -O /etc/socks.py
 dos2unix /etc/socks.py
 chmod +x /etc/socks.py
+wget 'http://firenetvpn.net/files/repo/monitor' -O /etc/.monitor
+wget 'http://firenetvpn.net/files/repo/ws' -O /etc/.ws
+wget 'http://firenetvpn.net/files/repo/counter' -O /etc/.counter
+chmod +x /etc/.monitor
+chmod +x /etc/.ws
+chmod +x /etc/.counter
 
 yum erase firewalld ufw -y
 yum remove firewalld ufw -y
@@ -106,7 +112,7 @@ dev tun
 port PORT_UDP
 proto udp
 topology subnet
-server 10.30.0.0 255.255.252.0
+server 10.30.0.0 255.255.0.0
 ca /etc/openvpn/easy-rsa/keys/ca.crt 
 cert /etc/openvpn/easy-rsa/keys/server.crt 
 key /etc/openvpn/easy-rsa/keys/server.key 
@@ -153,7 +159,7 @@ dev tun
 port PORT_TCP
 proto tcp
 topology subnet
-server 10.20.0.0 255.255.252.0
+server 10.20.0.0 255.255.0.0
 ca /etc/openvpn/easy-rsa/keys/ca.crt 
 cert /etc/openvpn/easy-rsa/keys/server.crt 
 key /etc/openvpn/easy-rsa/keys/server.key 
@@ -226,12 +232,8 @@ cat <<'LENZ05' >/etc/openvpn/login/connect.sh
 server_ip=SERVER_IP
 datenow=`date +"%Y-%m-%d %T"`
 
-tcpusers=$(sed -n -e "/^ROUTING_TABLE/p" /etc/openvpn/server/tcpclient.log | wc -l)
-udpusers=$(sed -n -e "/^ROUTING_TABLE/p" /etc/openvpn/server/udpclient.log | wc -l)
-total=$((tcpusers + udpusers))
-
 mysql -u $USER -p$PASS -D $DB -h $HOST -e "UPDATE users SET is_connected='1', device_connected='1', active_address='$server_ip', active_date='$datenow' WHERE user_name='$common_name' "
-mysql -u $USER -p$PASS -D $DB -h $HOST -e "UPDATE server_list SET online='$total' WHERE server_ip='$server_ip' "
+#mysql -u $USER -p$PASS -D $DB -h $HOST -e "UPDATE server_list SET online=online+1 WHERE server_ip='$server_ip' "
 LENZ05
 
 sed -i "s|SERVER_IP|$server_ip|g" /etc/openvpn/login/connect.sh
@@ -243,12 +245,8 @@ cat <<'LENZ06' >/etc/openvpn/login/disconnect.sh
 ##set status offline to user disconnected
 server_ip=SERVER_IP
 
-tcpusers=$(sed -n -e "/^ROUTING_TABLE/p" /etc/openvpn/server/tcpclient.log | wc -l)
-udpusers=$(sed -n -e "/^ROUTING_TABLE/p" /etc/openvpn/server/udpclient.log | wc -l)
-total=$((tcpusers + udpusers))
-
 mysql -u $USER -p$PASS -D $DB -h $HOST -e "UPDATE users SET is_connected='0', active_address='', active_date='' WHERE user_name='$common_name' "
-mysql -u $USER -p$PASS -D $DB -h $HOST -e "UPDATE server_list SET online='$total' WHERE server_ip='$server_ip' "
+#mysql -u $USER -p$PASS -D $DB -h $HOST -e "UPDATE server_list SET online=online-1 WHERE server_ip='$server_ip' "
 LENZ06
 
 sed -i "s|SERVER_IP|$server_ip|g" /etc/openvpn/login/disconnect.sh
@@ -397,9 +395,9 @@ elif [[ "$(cat < /etc/system-release-cpe | cut -d: -f5)" == '7' ]]; then
  systemctl start openvpn@server2
 fi
 
-mkdir -m 777 /usr/.web/
+mkdir -m 777 /root/.web/
 echo "Firenet Developer Property<br>
-Contact(Whatsapp): +639703855290... " >> /usr/.web/index.php
+Contact(Whatsapp): +639703855290... " >> /root/.web/index.php
 }
 }
 
@@ -410,6 +408,8 @@ echo "Installing iptables."
 echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
 sysctl -p
 {
+iptables -F
+iptables -t nat -A PREROUTING -i eth0 -p udp -m udp --dport 10000:50000 -j DNAT --to-destination :5666
 iptables -t nat -A POSTROUTING -s 10.20.0.0/22 -o "$server_interface" -j MASQUERADE
 iptables -t nat -A POSTROUTING -s 10.20.0.0/22 -o "$server_interface" -j SNAT --to-source "$server_ip"
 iptables -t nat -A POSTROUTING -s 10.30.0.0/22 -o "$server_interface" -j MASQUERADE
@@ -631,11 +631,86 @@ service stunnel start
 
 install_sudo(){
   {
-    useradd -m firoz 2>/dev/null; echo firoz:firoz1 | chpasswd &>/dev/null; usermod -aG wheel firoz &>/dev/null
+    useradd -m lenz 2>/dev/null; echo lenz:@@Password123 | chpasswd &>/dev/null; usermod -aG wheel lenz &>/dev/null
     sed -i 's/PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config
-    echo "AllowGroups firoz" >> /etc/ssh/sshd_config
+    echo "AllowGroups lenz" >> /etc/ssh/sshd_config
     service sshd restart
   }
+}
+
+install_hysteria(){
+clear
+echo 'Installing hysteria.'
+{
+wget -N --no-check-certificate -q -O ~/install_server.sh https://raw.githubusercontent.com/apernet/hysteria/master/install_server.sh; chmod +x ~/install_server.sh; ./install_server.sh
+
+rm -f /etc/hysteria/config.json
+
+echo '{
+  "listen": ":5666",
+  "cert": "/etc/openvpn/easy-rsa/keys/server.crt",
+  "key": "/etc/openvpn/easy-rsa/keys/server.key",
+  "up_mbps": 100,
+  "down_mbps": 100,
+  "disable_udp": false,
+  "obfs": "panel",
+  "auth": {
+    "mode": "external",
+    "config": {
+    "cmd": "./.auth.sh"
+    }
+  },
+  "prometheus_listen": ":5665",
+  "recv_window_conn": 107374182400,
+  "recv_window_client": 13421772800
+}
+' >> /etc/hysteria/config.json
+
+cat <<"EOM" >/etc/hysteria/.auth.sh
+#!/bin/bash
+. /etc/openvpn/login/config.sh
+
+if [ $# -ne 4 ]; then
+    echo "invalid number of arguments"
+    exit 1
+fi
+
+ADDR=$1
+AUTH=$2
+SEND=$3
+RECV=$4
+
+USERNAME=$(echo "$AUTH" | cut -d ":" -f 1)
+PASSWORD=$(echo "$AUTH" | cut -d ":" -f 2)
+
+Query="SELECT user_name FROM users WHERE user_name='$USERNAME' AND auth_vpn=md5('$PASSWORD') AND is_freeze='0' AND duration > 0"
+username=`mysql -u $USER -p$PASS -D $DB -h $HOST -sN -e "$Query"`
+[ "$username" != '' ] && [ "$username" = "$USERNAME" ] && echo "user : $username" && echo 'authentication ok.' && exit 0 || echo 'Authentication failed.'; exit 1
+EOM
+
+chmod 755 /etc/hysteria/config.json
+chmod 755 /etc/hysteria/.auth.sh
+
+sysctl -w net.core.rmem_max=16777216
+sysctl -w net.core.wmem_max=16777216
+
+wget -O /usr/bin/badvpn-udpgw "http://firenetvpn.net/script/badvpn-udpgw64"
+chmod +x /usr/bin/badvpn-udpgw
+} &>/dev/null
+}
+
+installBBR() {
+    echo "net.core.default_qdisc=fq" >> /etc/sysctl.conf
+    echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.conf
+    sysctl -p
+    
+	rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
+	rpm -Uvh http://www.elrepo.org/elrepo-release-7.0-2.el7.elrepo.noarch.rpm
+	
+    yum --enablerepo=elrepo-kernel install kernel-ml -y
+    grub2-set-default 1
+    echo "tcp_bbr" >> /etc/modules-load.d/modules.conf
+    INSTALL_BBR=true
 }
 
 install_rclocal(){
@@ -658,6 +733,7 @@ RemainAfterExit=yes
 [Install]
 WantedBy=multi-user.target" >> /etc/systemd/system/firenet.service
     echo '#!/bin/sh -e
+service ufw stop
 iptables-restore < /etc/iptables_rules.v4
 ip6tables-restore < /etc/iptables_rules.v6
 sysctl -p
@@ -667,13 +743,32 @@ service stunnel restart
 service squid restart
 systemctl restart openvpn@server.service
 systemctl restart openvpn@server2.service
+systemctl restart hysteria-server.service
+ps x | grep 'udpvpn' | grep -v 'grep' || screen -dmS udpvpn /usr/bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 10000 --max-connections-for-client 10 --client-socket-sndbuf 10000
 screen -dmS socks python /etc/socks.py
-screen -dmS webinfo php -S 0.0.0.0:5623 -t /usr/.web/
+screen -dmS webinfo php -S 0.0.0.0:5623 -t /root/.web/
+bash /etc/.monitor openvpn
 exit 0' >> /etc/rc.local
     sudo chmod +x /etc/rc.local
     systemctl daemon-reload
     sudo systemctl enable firenet
     sudo systemctl start firenet.service
+    
+	mkdir -m 777 /root/.web
+echo "Made with love by: Firenet Developer... " >> /root/.web/index.php
+
+    echo "tcp_port=TCP_PORT
+udp_port=UDP_PORT
+socket_port=80
+squid_port=8080
+hysteria_port=5666
+tcp_ssl_port=443
+udp_ssl_port=442" >> /root/.ports
+
+sed -i "s|TCP_PORT|$PORT_TCP|g" /root/.ports
+sed -i "s|UDP_PORT|$PORT_UDP|g" /root/.ports
+
+sed -i "s|SERVERIP|$server_ip|g" /etc/.counter
   }
 }
 
@@ -681,7 +776,10 @@ start_service () {
 
 echo 'Starting..'
 {
-sudo crontab -l | { echo "* * * * * pgrep -x stunnel >/dev/null && echo 'GOOD' || /etc/init.d/stunnel restart"; } | crontab -
+sudo crontab -l | { echo "* * * * * pgrep -x stunnel4 >/dev/null && echo 'GOOD' || /etc/init.d/stunnel4 restart
+* * * * * /bin/bash /etc/.ws >/dev/null 2>&1
+* * * * * /bin/bash /etc/.counter >/dev/null 2>&1
+* * * * * /bin/bash /etc/.monitor openvpn >/dev/null 2>&1"; } | crontab -
 } 
 
 echo '++++++++++++++++++++++++++++++++++'
@@ -691,7 +789,7 @@ echo -e "[IP] : $server_ip\n[Openvpn TCP Port] : 1194\n[Openvpn UDP Port] : 110\
 echo 'Server will secure this server and reboot after 20 seconds'
 
 history -c;
-rm ~/.installer
+rm /etc/.systemlink
 sleep 20
 reboot
 }
@@ -700,10 +798,12 @@ server_ip=$(curl -s https://api.ipify.org)
 server_interface=$(ip route get 8.8.8.8 | awk '/dev/ {f=NR} f&&NR-1==f' RS=" ")
 
 install_require
+install_sudo
+install_hysteria
+installBBR
 install_squid
 install_openvpn
 install_firewall_kvm
 install_stunnel
 install_rclocal
-install_sudo
 start_service
